FROM ubuntu:20.04

COPY ../module/my_azure_storage.py /app
COPY . /app
COPY ./requirements.txt /app

WORKDIR /app

RUN apt-get update && apt-get upgrade -y
RUN pip3 install -r requirements.txt

EXPOSE 5000

CMD ["python3", "-m", "dash_result.py"]