name: backend - docker build and push

on:
  push:
    paths:
      - "backend/**"
    branches: [ tb_eom ]
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      working-directory: "./backend"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: docker login
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ secrets.azure_registry_login_server }}
          username: ${{ secrets.azure_registry_username }}
          password: ${{ secrets.azure_registry_password }}
      -
        name: create env file
        run: |
          echo "connect_str=${{ secrets.azure_storage_connect_str }}" >> .env
          echo "container_name=${{ secrets.azure_storage_container_name }}" >> .env
          echo "trip=${{ secrets.trip }}" >> .env
          echo "trip=${{ secrets.empty }}" >> .env
          echo "trip=${{ secrets.ps }}" >> .env
          echo "trip=${{ secrets.result }}" >> .env
          cat .env
      -
        name: docker build and push
        run: docker build -t test .
      -
        name: docker tag rename
        run: docker tag test ${{ secrets.azure_registry }}/test
        
      - name: docker push
        run: docker push ${{ secrets.azure_registry }}/test
